---
title: "HW5"
author: "Collin Brehmer"
date: "11/6/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(dplyr)
library(tidyr)
library(lubridate)
library(stringr)
library(ggplot2)
```

# Read in raw data
```{r raw, message = FALSE, warning = TRUE}
homicides_raw <- read_csv("../data/homicide-data.csv")
```


# Clean data
```{r}
homicides <- homicides_raw %>% 
  unite(city_name, city, state, sep= ", ") %>%
  filter(city_name == "Baltimore, MD" & reported_date != is.na(reported_date)) %>%
  mutate(year = year(ymd(reported_date)),
         month = month(ymd(reported_date)),
         year_month = paste0(year, "-", month),
         year_month = ymd(year_month, truncated = 1)) %>% 
  group_by(year_month) %>% 
  count()

winter <- list(1,2,3,4,11,12)
summer <- list(5,6,7,8,9,10)

homicides <- homicides %>% 
  mutate(season = case_when(month(year_month) %in% winter ~ "Winter",
                            month(year_month) %in% summer ~"Summer"))
```


# Plot
```{r}
homicides %>% 
  ggplot(aes(y = n, x = year_month)) +
  geom_bar(aes(fill = season), stat = "identity") +
  geom_smooth(se = FALSE, method = "loess", span = .15) +
  scale_fill_manual(values = c("#D3D3D3","#ADD8E6")) +
  theme_dark()+
  theme(legend.title = element_blank(),
        legend.position = "bottom") +
  labs(y = "Monthly homicides", x = "Date")+
  scale_x_date()
```

